import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

# Paths
base_model_path = "models/llama-3.2-1b"   # downloaded base model folder
adapter_path    = "Dinesh2001/Llama3.2-1B-QLoRA-Explainer"  # adapter from HF

# Load tokenizer from local base model
tokenizer = AutoTokenizer.from_pretrained(base_model_path)

# Load base model on CPU from local path
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_path,
    device_map="cpu",            # force CPU
    torch_dtype=torch.float32    # no half precision on CPU
)

# Load adapter on top of base
model = PeftModel.from_pretrained(base_model, adapter_path)

# Example inference
prompt = """Explain the below predictions:

{
  "predicted_class": "early",
  "predicted_probabilities": {
    "early": 0.4811,
    "on_time": 0.0414,
    "delay": 0.4775
  },
  "top_positive_features": [
    {
      "order_item_discount": 0.1268
    },
    {
      "order_profit_per_order": 0.0878
    }
  ],
  "top_negative_features": [
    {
      "performance_score_shipping_hour": -0.0474
    },
    {
      "performance_score_customer_full_location": -0.1137
    }
  ]
}
"""

inputs = tokenizer(prompt, return_tensors="pt")

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=150,
        temperature=0.7,
        top_p=0.9,
        do_sample=True
    )

# print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# Get the number of tokens in the input
input_length = inputs["input_ids"].shape[1]

# Slice only the new tokens generated by the model
generated_tokens = outputs[0][input_length:]

# Decode only the generated part
generated_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)

print(generated_text)
